In [1]:
from selenium import webdriver 
import requests
from bs4 import BeautifulSoup
import pandas as pd

# 경쟁사 공부방 위치 크롤링

In [ ]:
driver = webdriver.Edge()
keyword = '푸르넷공부방'
kakao_url = f"https://map.kakao.com/?q={keyword}"

driver.get(kakao_url)
driver.get(kakao_url)

In [3]:
ind = 1  # 현재 복사한 순서
no = 1  # 1~5페이지 중 위치한 곳
page = 1  # 현재 페이지 번호
list2 = []  # 결과물이 저장되는 리스트

while 1:
    try:
        # 업체명, 주소
        title = driver.find_element(by='xpath',
                                    value = f'//*[@id="info.search.place.list"]/li[{ind}]/div[3]/strong/a[2]').text # 해당되는 것을 텍스트로 반환
        addr = driver.find_element(by='xpath',
                                   value = f'//*[@id="info.search.place.list"]/li[{ind}]/div[5]/div[2]/p[1]').text
        add_a = driver.find_element(by='xpath',
                                   value = f'//*[@id="info.search.place.list"]/li[{ind}]/div[5]/div[2]/p[2]').text
        
        list2.append([title, addr, add_a]) #리스트 마지막에 데이터 추가
        
        ind += 1
        
    except:
        # 더보기 버튼 찾기
        if driver.find_element(by='xpath',value = f'//*[@id="info.search.place.more"]').is_displayed(): # 해당되는 값이 있으면 True로 반환
            driver.find_element(by='xpath',value = f'//*[@id="info.search.place.more"]').click()
            no += 1
            ind = 1
            page += 1
            continue

        # 5페이지 단위마다 다음 페이지 버튼 누르기# 다음 페이지로 이동
        elif no >= 5:
            driver.find_element(by='xpath',value = f'//*[@id="info.search.page.next"]').click()
            no = 1
            ind = 1
            page += 1
            continue
            
        # 다음 페이지로 이동
        elif driver.find_element(by='xpath',value = f'//*[@id="info.search.page.no{no+1}"]').is_displayed():
            no += 1
            driver.find_element(by='xpath',value = f'//*[@id="info.search.page.no{no}"]').click()
            ind = 1
            page += 1
            continue
        
        # 더이상 이동할수 없을 경우 종료
        else:
            break

In [7]:
pd.DataFrame(list2)

               0                              1                 2
0         푸르넷공부방                 경기 광명시 오리로 374  (지번) 소하동 1242-13
1      푸르넷 소하공부방        경기 광명시 소하일로52번길 29 102호  (지번) 소하동 1311-13
2         푸르넷공부방          경기 안양시 만안구 충훈로71번길 36    (지번) 석수동 782-9
3         푸르넷공부방  경기 안양시 만안구 충훈로 51 석수아이파크 109동      (지번) 석수동 794
4      푸르넷 수정공부방       경기 광명시 하안로 364 904동 804호       (지번) 하안동 13
..           ...                            ...               ...
340  에벤에셀 푸르넷공부방                  울산 동구 꽃바위5길 9  (지번) 방어동 1000-10
341   푸르넷 1등 공부방                 울산 동구 꽃바위5길 27    (지번) 방어동 992-2
342    푸르넷일오삼공부방                  울산 동구 양지1길 28   (지번) 화정동 854-17
343       푸르넷공부방          제주특별자치도 서귀포시 토평남로 104   (지번) 토평동 1262-2
344     아라푸르넷공부방       제주특별자치도 제주시 아란8길 10 301호  (지번) 아라일동 6093-5

[345 rows x 3 columns]

# 당사 공부방 위치 크롤링

In [56]:
driver = webdriver.Edge()

In [120]:
import time
ind = 289543
ind_2 = 1



while 1:
    
    try:
        smart_url = f'https://www.smarthb-math.co.kr/franchise/find.php?ptype=view&idx={ind}&page=115&code=franchiseeLocation&searchopt=&'
        driver.get(smart_url)

        name_A = driver.find_element(by='xpath',value = f'//*[@id="wrap"]/div[3]/div/table/tbody/tr[1]/th').text
        adress = driver.find_element(by='xpath',value = f'//*[@id="wrap"]/div[3]/div/table/tbody/tr[2]/td').text
        list1.append([name_A,adress])
        ind -= 1
        

    except:
        break

In [88]:
df=pd.DataFrame(list1)